version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: stellar_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stellar_sales
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: stellar_qdrant
    ports:
      - '6333:6333'
    volumes:
      - qdrant_data:/qdrant/storage

  neo4j:
    image: neo4j:5
    container_name: stellar_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  qdrant_data:
  neo4j_data:
