from typing import TypedDict, List, Dict, Any, Optional
from pathlib import Path

class AgentState(TypedDict):
    """
    Represents the unified state for both the ingestion pipeline and the
    reasoning engine. It is designed for a gradual, backward-compatible
    migration to the new agentic architecture.

    Sprint 01: Intelligence First architecture with semantic memory
    Sprint 02: Reasoning Engine with cognitive nodes (Gatekeeper, Planner, Auditor, Router)
    """
    # --- Universal Fields ---
    file_path: Optional[Path]
    transcript_id: Optional[str]  # Changed from int to str to match header ID
    chunks: Optional[List[str]]

    # --- Ingestion & Legacy Fields (from Sprint 1) ---
    raw_text: Optional[str]
    structured_dialogue: Optional[List[Dict[str, Any]]]
    conversation_phases: Optional[List[Dict[str, Any]]]  # RE-ADDED for compatibility
    extracted_data: Optional[Dict[str, Any]]  # PRESERVED for backward compatibility
    crm_data: Optional[Dict[str, Any]]
    email_draft: Optional[str]
    social_content: Optional[Dict[str, Any]]
    coaching_feedback: Optional[Dict[str, Any]]
    db_save_status: Optional[Dict[str, Any]]  # RE-ADDED for compatibility
    historian_status: Optional[Dict[str, Any]]  # RE-ADDED for compatibility

    # --- Reasoning Engine & "Intelligence First" Fields ---
    original_request: Optional[str]  # User's original query for reasoning engine
    extracted_entities: Optional[Dict[str, Any]]  # From KnowledgeAnalystAgent
    plan: Optional[List[str]]  # Generated by PlannerAgent
    intermediate_steps: Optional[List[Dict[str, Any]]]  # Actions taken by RouterAgent
    verification_history: Optional[List[Dict[str, Any]]]  # Results from AuditorAgent
    clarification_question: Optional[str]  # From GatekeeperAgent if request is ambiguous
    final_response: Optional[str]  # Final answer to user's request